---
settings:
  name: Cloud Volumes ONTAP 9.13.0 release notes
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - name: Cloud Volumes ONTAP
    url: "/cloud-volumes-ontap-9130-relnotes"
    version-number: 9.13.0
  - name: Cloud Volumes ONTAP
    url: "/cloud-volumes-ontap-relnotes"
    version-number: 9.13.1
  - name: Cloud Volumes ONTAP
    url: "/cloud-volumes-ontap-9121-relnotes"
    version-number: 9.12.1
  - name: Cloud Volumes ONTAP
    url: "/cloud-volumes-ontap-9120-relnotes"
    version-number: 9.12.0
  - name: Cloud Volumes ONTAP
    url: "/cloud-volumes-ontap-9111-relnotes"
    version-number: 9.11.1
  - name: Cloud Volumes ONTAP
    url: "/cloud-volumes-ontap-9110-relnotes"
    version-number: 9.11.0
  - name: Cloud Volumes ONTAP
    url: "/cloud-volumes-ontap-9101-relnotes"
    version-number: 9.10.1
  - name: Cloud Volumes ONTAP
    url: "/cloud-volumes-ontap-9100-relnotes"
    version-number: 9.10.0
  - name: Cloud Volumes ONTAP
    url: "/cloud-volumes-ontap-991-relnotes"
    version-number: 9.9.1
  - name: Cloud Volumes ONTAP
    url: "/cloud-volumes-ontap-990-relnotes"
    version-number: 9.9.0
  - name: Cloud Volumes ONTAP
    url: "/cloud-volumes-ontap-98-relnotes"
    version-number: '9.8'
  - name: Cloud Volumes ONTAP
    url: "/cloud-volumes-ontap-97-relnotes"
    version-number: '9.7'
  - name: Cloud Volumes ONTAP
    url: "/cloud-volumes-ontap-96-relnotes"
    version-number: '9.6'
  - name: Cloud Volumes ONTAP
    url: "/cloud-volumes-ontap-95-relnotes"
    version-number: '9.5'
  - name: Cloud Volumes ONTAP
    url: "/cloud-volumes-ontap-94-relnotes"
    version-number: '9.4'
  - name: ONTAP Cloud
    url: "/cloud-volumes-ontap-93-relnotes"
    version-number: '9.3'
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: Versionshinweise zu Hause
    url: "/index.html"
  - title: Was ist neu
    url: "/reference-new.html"
  - title: Übersicht über die Lizenzierung
    url: "/concept-licensing.html"
  - title: Unterstützte Konfigurationen
    entries:
    - title: AWS
      url: "/reference-configs-aws.html"
    - title: Azure
      url: "/reference-configs-azure.html"
    - title: Google Cloud
      url: "/reference-configs-gcp.html"
  - title: Storage-Beschränkungen
    entries:
    - title: AWS
      url: "/reference-limits-aws.html"
    - title: Azure
      url: "/reference-limits-azure.html"
    - title: Google Cloud
      url: "/reference-limits-gcp.html"
  - title: Bekannte Probleme
    url: "/reference-issues.html"
  - title: Bekannte Einschränkungen
    entries:
    - title: Allgemeine Einschränkungen
      url: "/reference-limitations.html"
    - title: Einschränkungen in AWS
      url: "/reference-limitations-aws.html"
    - title: Einschränkungen in Azure
      url: "/reference-limitations-azure.html"
    - title: Beschränkungen in Google Cloud
      url: "/reference-limitations-gcp.html"
  - title: Integration von Cloud-Providern
    url: "/reference-provider-integrations.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: cloud-manager-family
  sidebar_label: Alle BlueXP-Dokumentationen
